name: Animavita Lint

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  lint:
    name: Lint all packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache dir
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn.lock
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn config set unsafe-disable-integrity-migration true -g
          yarn install --frozen-lockfile --production=false --non-interactive --cache-folder $(yarn cache dir)
      - name: Relay
        run: |
          yarn relay
      - name: Create environment.ts files
        run: |
          cp packages/expo/environment.example.ts packages/expo/environment.ts &&
          cp packages/relay/environment.example.ts packages/relay/environment.ts
      - name: Lint
        run: |
          yarn lint:ci
