name: Animavita GraphQL Tests

on:
  push:
    paths:
      - '.github/workflows/test-graphql.yml'
      - 'packages/graphql/**'
      - 'packages/babel/**'
      - 'packages/eslint-config/**'
    branches-ignore:
      - 'master'

jobs:
  test-graphql:
    name: GraphQL Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.14'
      - name: Get yarn cache dir
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn.lock
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn config set unsafe-disable-integrity-migration true -g
          yarn install --frozen-lockfile --production=false --non-interactive --cache-folder $(yarn cache dir)
      - name: Test GraphQL
        run: |
          yarn test:graphql --ci --maxWorkers=4 --coverage --reporters=jest-junit --forceExit
        env:
          JEST_SUITE_NAME: 'Animavita GraphQL Tests'
          JEST_JUNIT_OUTPUT_DIR: './reports'
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
